default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: flashcards_development
  username: user
  password: 12345
  host: localhost
  port: 5432

test:
  <<: *default
  database: flashcards_test
  username: test_user
  password: 12345